<a href="https://colab.research.google.com/github/maydrop172/Tugas_Pertemuan2_PCd/blob/main/Soal1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.ndimage import label

# Matriks biner dari soal
img = np.array([
[0,0,0,0,0,0,0,0,0,0],
[0,1,1,1,0,0,0,1,1,0],
[0,1,1,1,0,0,0,1,1,0],
[0,1,1,1,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0],
[0,0,1,1,0,0,1,1,1,0],
[0,0,1,1,0,0,1,1,1,0],
[0,0,0,0,0,0,1,1,1,0],
[0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0]
])

# Struktur konektivitas 4-neighbour
structure = np.array([
[0,1,0],
[1,1,1],
[0,1,0]
])

# Pelabelan komponen terhubung
labeled, num_objects = label(img, structure)

# Menampilkan hasil
print("Jumlah objek (4-connectivity):", num_objects)
print("Matrix Label:")
print(labeled)

Jumlah objek (4-connectivity): 4
Matrix Label:
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 2 2 0]
 [0 1 1 1 0 0 0 2 2 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 3 3 0 0 4 4 4 0]
 [0 0 3 3 0 0 4 4 4 0]
 [0 0 0 0 0 0 4 4 4 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
